// Code generated by "stringer -type=digoutCol -trimprefix=digout"; DO NOT EDIT.

package sheetreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[digoutTag-0]
	_ = x[digoutDescription-1]
	_ = x[digoutOutput-2]
	_ = x[digoutOutputAddress-3]
	_ = x[digoutFeedbackTag-4]
	_ = x[digoutFeedbackAddress-5]
	_ = x[digoutBreakerTag-6]
	_ = x[digoutBreakerAddress-7]
	_ = x[digoutMonitoringTime-8]
}

const _digoutCol_name = "TagDescriptionOutputOutputAddressFeedbackTagFeedbackAddressBreakerTagBreakerAddressMonitoringTime"

var _digoutCol_index = [...]uint8{0, 3, 14, 20, 33, 44, 59, 69, 83, 97}

func (i digoutCol) String() string {
	if i < 0 || i >= digoutCol(len(_digoutCol_index)-1) {
		return "digoutCol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _digoutCol_name[_digoutCol_index[i]:_digoutCol_index[i+1]]
}
