// Code generated by "stringer -type=freqMotorCol -trimprefix=freqMotor"; DO NOT EDIT.

package sheetreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[freqMotorTag-0]
	_ = x[freqMotorDescription-1]
	_ = x[freqMotorOutput-2]
	_ = x[freqMotorOutputAddress-3]
	_ = x[freqMotorPqwAddress-4]
	_ = x[freqMotorDanfoss-5]
	_ = x[freqMotorFeedbackTag-6]
	_ = x[freqMotorFeedbackAddress-7]
	_ = x[freqMotorBreakerTag-8]
	_ = x[freqMotorBreakerAddress-9]
	_ = x[freqMotorSwitchTag-10]
	_ = x[freqMotorSwitchAddress-11]
	_ = x[freqMotorAlarmTag-12]
	_ = x[freqMotorAlarmAddress-13]
}

const _freqMotorCol_name = "TagDescriptionOutputOutputAddressPqwAddressDanfossFeedbackTagFeedbackAddressBreakerTagBreakerAddressSwitchTagSwitchAddressAlarmTagAlarmAddress"

var _freqMotorCol_index = [...]uint8{0, 3, 14, 20, 33, 43, 50, 61, 76, 86, 100, 109, 122, 130, 142}

func (i freqMotorCol) String() string {
	if i < 0 || i >= freqMotorCol(len(_freqMotorCol_index)-1) {
		return "freqMotorCol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _freqMotorCol_name[_freqMotorCol_index[i]:_freqMotorCol_index[i+1]]
}
