// Code generated by "stringer -type=measmonCol -trimprefix=measmon"; DO NOT EDIT.

package sheetreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[measmonTag-0]
	_ = x[measmonDescription-1]
	_ = x[measmonAddress-2]
	_ = x[measmonUnit-3]
	_ = x[measmonDirect-4]
	_ = x[measmonMin-5]
	_ = x[measmonMax-6]
}

const _measmonCol_name = "TagDescriptionAddressUnitDirectMinMax"

var _measmonCol_index = [...]uint8{0, 3, 14, 21, 25, 31, 34, 37}

func (i measmonCol) String() string {
	if i < 0 || i >= measmonCol(len(_measmonCol_index)-1) {
		return "measmonCol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _measmonCol_name[_measmonCol_index[i]:_measmonCol_index[i+1]]
}
