// Code generated by "stringer -type=motorCol -trimprefix=motor"; DO NOT EDIT.

package sheetreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[motorTag-0]
	_ = x[motorAddress-1]
	_ = x[motorDescription-2]
	_ = x[motorFeedbackTag-3]
	_ = x[motorFeedbackAddress-4]
	_ = x[motorBreakerTag-5]
	_ = x[motorBreakerAddress-6]
	_ = x[motorSwitchTag-7]
	_ = x[motorSwitchAddress-8]
}

const _motorCol_name = "TagAddressDescriptionFeedbackTagFeedbackAddressBreakerTagBreakerAddressSwitchTagSwitchAddress"

var _motorCol_index = [...]uint8{0, 3, 10, 21, 32, 47, 57, 71, 80, 93}

func (i motorCol) String() string {
	if i < 0 || i >= motorCol(len(_motorCol_index)-1) {
		return "motorCol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _motorCol_name[_motorCol_index[i]:_motorCol_index[i+1]]
}
