// Code generated by "stringer -type=motorCol -trimprefix=motor"; DO NOT EDIT.

package sheetreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[motorTag-0]
	_ = x[motorDescription-1]
	_ = x[motorOutput-2]
	_ = x[motorOutputAddress-3]
	_ = x[motorFeedbackTag-4]
	_ = x[motorFeedbackAddress-5]
	_ = x[motorBreakerTag-6]
	_ = x[motorBreakerAddress-7]
	_ = x[motorSwitchTag-8]
	_ = x[motorSwitchAddress-9]
}

const _motorCol_name = "TagDescriptionOutputOutputAddressFeedbackTagFeedbackAddressBreakerTagBreakerAddressSwitchTagSwitchAddress"

var _motorCol_index = [...]uint8{0, 3, 14, 20, 33, 44, 59, 69, 83, 92, 105}

func (i motorCol) String() string {
	if i < 0 || i >= motorCol(len(_motorCol_index)-1) {
		return "motorCol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _motorCol_name[_motorCol_index[i]:_motorCol_index[i+1]]
}
