// Code generated by "stringer -type=valveCol -trimprefix=valve"; DO NOT EDIT.

package sheetreader

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[valveTag-0]
	_ = x[valveDescription-1]
	_ = x[valveAddress-2]
	_ = x[valveFeedbackOpenTag-3]
	_ = x[valveFeedbackOpenAddress-4]
	_ = x[valveFeedbackClosedTag-5]
	_ = x[valveFeedbackClosedAddress-6]
	_ = x[valveMonitoringTimeOpen-7]
	_ = x[valveMonitoringTimeClose-8]
}

const _valveCol_name = "TagDescriptionAddressFeedbackOpenTagFeedbackOpenAddressFeedbackClosedTagFeedbackClosedAddressMonitoringTimeOpenMonitoringTimeClose"

var _valveCol_index = [...]uint8{0, 3, 14, 21, 36, 55, 72, 93, 111, 130}

func (i valveCol) String() string {
	if i < 0 || i >= valveCol(len(_valveCol_index)-1) {
		return "valveCol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _valveCol_name[_valveCol_index[i]:_valveCol_index[i+1]]
}
